//// Decompiled by Jad v1.5.8g. Copyright 2001 Pavel Kouznetsov.
//// Jad home page: http://www.kpdus.com/jad.html
//// Decompiler options: packimports(3)
//// Source File Name:   BRBW471.java
//
//package com.ibm.bsch.client.bmlclasses;
//
//import com.ibm.dse.gui.OperationPanel;
//import com.ibm.dse.gui.extensions.*;
//import java.awt.Component;
//import java.io.PrintStream;
//import javax.swing.*;
//
//public class BRBW471
//{
//
//    public BRBW471()
//    {
//        panelPadre = new BSCHOperationPanel();
//    }
//
//    public void setClassLoader(ClassLoader classloader)
//    {
//        classLoader = classloader;
//    }
//
//    public BSCHOperationPanel exec()
//    {
//        try
//        {
//            panelPadre.setOperationName("dummyOp");
//            panelPadre.setName("BRBW471");
//            panelPadre.setTitle("Impress\343o de Abertura de Conta - PF");
//            panelPadre.setDimensions("0,0,475,458,C,C");
//            panelPadre.setProcessParameters("GLOBAL(CCC(1-4)*VGENTID),GLOBAL(CCC(5-8)*VGCENTER),GLOBAL(TFENTIDAD*VGENTID),GLOBAL(BCO*VGENTID),GLOBAL(AGE*VGCENTER)");
//            panelPadre.setPreViewAction("com.ibm.bsch.client.launcher.LauncherCrossRelationByName");
//            panelPadre.setPreViewData("Relation1");
//            BSCHTitledEmbeddedPanel bschtitledembeddedpanel = new BSCHTitledEmbeddedPanel();
//            bschtitledembeddedpanel.setName("CAJA-AGRUPACION-2");
//            bschtitledembeddedpanel.setText("Dados de Pesquisa");
//            bschtitledembeddedpanel.setDimensions("11,3,444,95");
//            panelPadre.add(bschtitledembeddedpanel);
//            BSCHRadioButton bschradiobutton = new BSCHRadioButton();
//            bschradiobutton.setName("CTAABER-1");
//            bschradiobutton.setGroupId("QtButtonGroup1");
//            bschradiobutton.setDimensions("34,25,101,14");
//            bschradiobutton.setSelected("y");
//            bschradiobutton.setText("Conta Aberta");
//            panelPadre.add(bschradiobutton);
//            BSCHRadioButton bschradiobutton1 = new BSCHRadioButton();
//            bschradiobutton1.setName("CTAPROP-2");
//            bschradiobutton1.setGroupId("QtButtonGroup1");
//            bschradiobutton1.setDimensions("153,24,217,14");
//            bschradiobutton1.setText("Proposta Pendente de Aprova\347\343o");
//            panelPadre.add(bschradiobutton1);
//            BSCHLabel bschlabel = new BSCHLabel();
//            bschlabel.setName("CABECERA-1");
//            bschlabel.setText("Deseja imprimir os formul\341rios abaixo:");
//            bschlabel.setDimensions("26,117,182,15");
//            panelPadre.add(bschlabel);
//            BSCHTextFieldComboBoxRepetirCuentaBAPasivo bschtextfieldcomboboxrepetircuentabapasivo = new BSCHTextFieldComboBoxRepetirCuentaBAPasivo();
//            bschtextfieldcomboboxrepetircuentabapasivo.setName("CCCABE-1");
//            bschtextfieldcomboboxrepetircuentabapasivo.setDataName("CCC");
//            bschtextfieldcomboboxrepetircuentabapasivo.setDimensions("35,45,175,35");
//            bschtextfieldcomboboxrepetircuentabapasivo.setVisible(false);
//            bschtextfieldcomboboxrepetircuentabapasivo.setFocusLostProcess("com.ibm.bsch.client.launcher.LauncherCrossRelationByName");
//            bschtextfieldcomboboxrepetircuentabapasivo.setFocusLostProcessData("Relation31");
//            bschtextfieldcomboboxrepetircuentabapasivo.setWindowPE("BRPE005");
//            panelPadre.add(bschtextfieldcomboboxrepetircuentabapasivo);
//            BSCHTextFieldComboBoxRepetirCuentaBAPasivo bschtextfieldcomboboxrepetircuentabapasivo1 = new BSCHTextFieldComboBoxRepetirCuentaBAPasivo();
//            bschtextfieldcomboboxrepetircuentabapasivo1.setName("CCCPRO-1");
//            bschtextfieldcomboboxrepetircuentabapasivo1.setDataName("CCC");
//            bschtextfieldcomboboxrepetircuentabapasivo1.setDimensions("35,46,175,35");
//            bschtextfieldcomboboxrepetircuentabapasivo1.setPrismaticosVisible("n");
//            bschtextfieldcomboboxrepetircuentabapasivo1.setFocusLostProcess("com.ibm.bsch.client.launcher.LauncherCrossRelationByName");
//            bschtextfieldcomboboxrepetircuentabapasivo1.setFocusLostProcessData("Relation31");
//            bschtextfieldcomboboxrepetircuentabapasivo1.setTrxPE("NOTX");
//            bschtextfieldcomboboxrepetircuentabapasivo1.setWindowPE("BRPE005");
//            panelPadre.add(bschtextfieldcomboboxrepetircuentabapasivo1);
//            BSCHButton bschbutton = new BSCHButton();
//            bschbutton.setName("NA-BUSCAR-1");
//            bschbutton.setClickProcess("com.ibm.bsch.client.launcher.LauncherCrossRelationByName");
//            bschbutton.setClickProcessData("Relation15,Relation16");
//            bschbutton.setClickProcess("com.ibm.bsch.client.launcher.ExecuteTransaction");
//            bschbutton.setClickProcessData("BW87,INDTELA*'PF',INDACAO*'PES',TIPPESQ,BANCO*CCC(1-4),AGENCIA*CCC(5-8),CONTA*CCC(9-20),INCCBCE*CHKCCB1");
//            bschbutton.setClickProcessOutData("ALL,CCBPAC");
//            bschbutton.setClickProcess("com.ibm.bsch.client.launcher.LauncherCrossRelationByName");
//            bschbutton.setClickProcessData("Relation30,Relation44,Relation45");
//            bschbutton.setButtonType("Buscar");
//            bschbutton.setDimensions("338,58,100,21");
//            bschbutton.setText("Pesquisar");
//            panelPadre.add(bschbutton);
//            BSCHCheckBox bschcheckbox = new BSCHCheckBox();
//            bschcheckbox.setName("CHKPAC-1");
//            bschcheckbox.setDataName("CHKPAC");
//            bschcheckbox.setDimensions("26,139,15,14");
//            panelPadre.add(bschcheckbox);
//            BSCHCheckBox bschcheckbox1 = new BSCHCheckBox();
//            bschcheckbox1.setName("CHKCCB1-1");
//            bschcheckbox1.setDataName("CHKCCB1");
//            bschcheckbox1.setDimensions("26,179,15,14");
//            panelPadre.add(bschcheckbox1);
//            BSCHCheckBox bschcheckbox2 = new BSCHCheckBox();
//            bschcheckbox2.setName("CHKCCB2-1");
//            bschcheckbox2.setDataName("CHKCCB2");
//            bschcheckbox2.setDimensions("26,201,13,14");
//            panelPadre.add(bschcheckbox2);
//            BSCHCheckBox bschcheckbox3 = new BSCHCheckBox();
//            bschcheckbox3.setName("CHKTPCT-1");
//            bschcheckbox3.setDataName("CHKTPCT");
//            bschcheckbox3.setDimensions("26,265,13,14");
//            panelPadre.add(bschcheckbox3);
//            BSCHCheckBox bschcheckbox4 = new BSCHCheckBox();
//            bschcheckbox4.setName("CHKPROT-1");
//            bschcheckbox4.setDataName("CHKPROT");
//            bschcheckbox4.setBehaviour("RDONLY");
//            bschcheckbox4.setDimensions("26,285,15,14");
//            panelPadre.add(bschcheckbox4);
//            BSCHCheckBox bschcheckbox5 = new BSCHCheckBox();
//            bschcheckbox5.setName("CHKFHCD-1");
//            bschcheckbox5.setDataName("CHKFHCD");
//            bschcheckbox5.setDimensions("26,307,13,14");
//            panelPadre.add(bschcheckbox5);
//            BSCHLabel bschlabel1 = new BSCHLabel();
//            bschlabel1.setName("L-REPRES-1");
//            bschlabel1.setText("");
//            bschlabel1.setDimensions("373,290,0,11");
//            bschlabel1.setBehaviour("RDONLY");
//            panelPadre.add(bschlabel1);
//            BSCHButtonTextField bschbuttontextfield = new BSCHButtonTextField();
//            bschbuttontextfield.setName("REPRES-1");
//            bschbuttontextfield.setClickProcess("com.ibm.bsch.client.launcher.ModalWindowOperation");
//            bschbuttontextfield.setClickProcessData("BRBW473,ALL");
//            bschbuttontextfield.setClickProcessOutData("QTDFICH");
//            bschbuttontextfield.setDataName("QTDFICH");
//            bschbuttontextfield.setType("NUMERIC");
//            bschbuttontextfield.setBehaviour("RDONLY");
//            bschbuttontextfield.setDimensions("371,306,74,16");
//            bschbuttontextfield.setMaxChars("10");
//            panelPadre.add(bschbuttontextfield);
//            BSCHCheckBox bschcheckbox6 = new BSCHCheckBox();
//            bschcheckbox6.setName("CHKTRSF-1");
//            bschcheckbox6.setDataName("CHKTRSF");
//            bschcheckbox6.setBehaviour("RDONLY");
//            bschcheckbox6.setDimensions("26,329,13,14");
//            panelPadre.add(bschcheckbox6);
//            BSCHTitledEmbeddedPanel bschtitledembeddedpanel1 = new BSCHTitledEmbeddedPanel();
//            bschtitledembeddedpanel1.setName("CAJA-AGRUPACION-3");
//            bschtitledembeddedpanel1.setText("Impress\343o do Dossi\352");
//            bschtitledembeddedpanel1.setDimensions("11,97,445,324");
//            panelPadre.add(bschtitledembeddedpanel1);
//            BSCHCheckBox bschcheckbox7 = new BSCHCheckBox();
//            bschcheckbox7.setName("CHKCCB3-1");
//            bschcheckbox7.setDataName("CHKCCB3");
//            bschcheckbox7.setBehaviour("RDONLY");
//            bschcheckbox7.setDimensions("26,223,17,14");
//            panelPadre.add(bschcheckbox7);
//            BSCHLabel bschlabel2 = new BSCHLabel();
//            bschlabel2.setName("L-NOMPAC-1");
//            bschlabel2.setText("");
//            bschlabel2.setDimensions("43,125,0,15");
//            bschlabel2.setBehaviour("RDONLY");
//            panelPadre.add(bschlabel2);
//            BSCHTextField bschtextfield = new BSCHTextField();
//            bschtextfield.setName("NOMPAC-1");
//            bschtextfield.setDataName("NOMPAC");
//            bschtextfield.setBehaviour("RDONLY");
//            bschtextfield.setType("ALPHANUMERIC");
//            bschtextfield.setMaxChars(300);
//            bschtextfield.setDimensions("43,140,400,16");
//            panelPadre.add(bschtextfield);
//            BSCHLabel bschlabel3 = new BSCHLabel();
//            bschlabel3.setName("L-NOMCCB1-1");
//            bschlabel3.setText("");
//            bschlabel3.setDimensions("43,165,0,15");
//            bschlabel3.setBehaviour("RDONLY");
//            panelPadre.add(bschlabel3);
//            BSCHTextField bschtextfield1 = new BSCHTextField();
//            bschtextfield1.setName("NOMCCB1-1");
//            bschtextfield1.setDataName("NOMCCB1");
//            bschtextfield1.setBehaviour("RDONLY");
//            bschtextfield1.setType("ALPHANUMERIC");
//            bschtextfield1.setMaxChars(300);
//            bschtextfield1.setDimensions("43,180,400,16");
//            panelPadre.add(bschtextfield1);
//            BSCHLabel bschlabel4 = new BSCHLabel();
//            bschlabel4.setName("L-NOMCCB2-1");
//            bschlabel4.setText("");
//            bschlabel4.setDimensions("43,187,0,15");
//            bschlabel4.setBehaviour("RDONLY");
//            panelPadre.add(bschlabel4);
//            BSCHTextField bschtextfield2 = new BSCHTextField();
//            bschtextfield2.setName("NOMCCB2-1");
//            bschtextfield2.setDataName("NOMCCB2");
//            bschtextfield2.setBehaviour("RDONLY");
//            bschtextfield2.setType("ALPHANUMERIC");
//            bschtextfield2.setMaxChars(300);
//            bschtextfield2.setDimensions("43,202,400,16");
//            panelPadre.add(bschtextfield2);
//            BSCHLabel bschlabel5 = new BSCHLabel();
//            bschlabel5.setName("L-NOMTPCT-1");
//            bschlabel5.setText("");
//            bschlabel5.setDimensions("43,248,0,15");
//            bschlabel5.setBehaviour("RDONLY");
//            panelPadre.add(bschlabel5);
//            BSCHTextField bschtextfield3 = new BSCHTextField();
//            bschtextfield3.setName("NOMTPCT-1");
//            bschtextfield3.setDataName("NOMTPCT");
//            bschtextfield3.setBehaviour("RDONLY");
//            bschtextfield3.setType("ALPHANUMERIC");
//            bschtextfield3.setMaxChars(300);
//            bschtextfield3.setDimensions("43,263,400,16");
//            panelPadre.add(bschtextfield3);
//            BSCHLabel bschlabel6 = new BSCHLabel();
//            bschlabel6.setName("L-NOMPROT-1");
//            bschlabel6.setText("");
//            bschlabel6.setDimensions("43,269,0,15");
//            bschlabel6.setBehaviour("RDONLY");
//            panelPadre.add(bschlabel6);
//            BSCHTextField bschtextfield4 = new BSCHTextField();
//            bschtextfield4.setName("NOMPROT-1");
//            bschtextfield4.setDataName("NOMPROT");
//            bschtextfield4.setBehaviour("RDONLY");
//            bschtextfield4.setType("ALPHANUMERIC");
//            bschtextfield4.setMaxChars(300);
//            bschtextfield4.setDimensions("43,284,401,16");
//            panelPadre.add(bschtextfield4);
//            BSCHLabel bschlabel7 = new BSCHLabel();
//            bschlabel7.setName("L-NOMFHCD-1");
//            bschlabel7.setText("");
//            bschlabel7.setDimensions("43,291,0,15");
//            bschlabel7.setBehaviour("RDONLY");
//            panelPadre.add(bschlabel7);
//            BSCHTextField bschtextfield5 = new BSCHTextField();
//            bschtextfield5.setName("NOMFHCD-1");
//            bschtextfield5.setDataName("NOMFHCD");
//            bschtextfield5.setBehaviour("RDONLY");
//            bschtextfield5.setType("ALPHANUMERIC");
//            bschtextfield5.setMaxChars(300);
//            bschtextfield5.setDimensions("43,306,318,16");
//            panelPadre.add(bschtextfield5);
//            BSCHLabel bschlabel8 = new BSCHLabel();
//            bschlabel8.setName("L-NOMCCB3-1");
//            bschlabel8.setText("");
//            bschlabel8.setDimensions("43,208,0,15");
//            bschlabel8.setBehaviour("RDONLY");
//            panelPadre.add(bschlabel8);
//            BSCHTextField bschtextfield6 = new BSCHTextField();
//            bschtextfield6.setName("NOMCCB3-1");
//            bschtextfield6.setDataName("NOMCCB3");
//            bschtextfield6.setBehaviour("RDONLY");
//            bschtextfield6.setType("ALPHANUMERIC");
//            bschtextfield6.setMaxChars(300);
//            bschtextfield6.setDimensions("43,223,400,16");
//            panelPadre.add(bschtextfield6);
//            BSCHLabel bschlabel9 = new BSCHLabel();
//            bschlabel9.setName("L-BRANCO-1");
//            bschlabel9.setText("");
//            bschlabel9.setDimensions("283,864,0,15");
//            bschlabel9.setBehaviour("OPT");
//            panelPadre.add(bschlabel9);
//            BSCHTextField bschtextfield7 = new BSCHTextField();
//            bschtextfield7.setName("BRANCO-1");
//            bschtextfield7.setDataName("BRANCO");
//            bschtextfield7.setType("ALPHANUMERIC");
//            bschtextfield7.setMaxChars(300);
//            bschtextfield7.setDefaultValue("123");
//            bschtextfield7.setDimensions("283,501,19,10");
//            panelPadre.add(bschtextfield7);
//            BSCHCheckBox bschcheckbox8 = new BSCHCheckBox();
//            bschcheckbox8.setName("CHKCCB4-1");
//            bschcheckbox8.setDataName("CHKCCB4");
//            bschcheckbox8.setDimensions("26,243,14,14");
//            panelPadre.add(bschcheckbox8);
//            BSCHLabel bschlabel10 = new BSCHLabel();
//            bschlabel10.setName("L-NOMCCB4-1");
//            bschlabel10.setText("");
//            bschlabel10.setDimensions("43,228,0,15");
//            bschlabel10.setBehaviour("RDONLY");
//            panelPadre.add(bschlabel10);
//            BSCHTextField bschtextfield8 = new BSCHTextField();
//            bschtextfield8.setName("NOMCCB4-1");
//            bschtextfield8.setDataName("NOMCCB4");
//            bschtextfield8.setBehaviour("RDONLY");
//            bschtextfield8.setType("ALPHANUMERIC");
//            bschtextfield8.setMaxChars(300);
//            bschtextfield8.setDimensions("43,243,400,16");
//            panelPadre.add(bschtextfield8);
//            BSCHLabel bschlabel11 = new BSCHLabel();
//            bschlabel11.setName("L-NOMMPPF-2");
//            bschlabel11.setText("");
//            bschlabel11.setDimensions("43,334,0,15");
//            bschlabel11.setBehaviour("RDONLY");
//            panelPadre.add(bschlabel11);
//            BSCHTextField bschtextfield9 = new BSCHTextField();
//            bschtextfield9.setName("NOMMPPF-2");
//            bschtextfield9.setDataName("NOMMPPF");
//            bschtextfield9.setBehaviour("RDONLY");
//            bschtextfield9.setType("ALPHANUMERIC");
//            bschtextfield9.setMaxChars(120);
//            bschtextfield9.setDimensions("43,349,399,16");
//            panelPadre.add(bschtextfield9);
//            BSCHCheckBox bschcheckbox9 = new BSCHCheckBox();
//            bschcheckbox9.setName("CHKMPPF-2");
//            bschcheckbox9.setDataName("CHKMPPF");
//            bschcheckbox9.setBehaviour("RDONLY");
//            bschcheckbox9.setDimensions("26,349,13,14");
//            panelPadre.add(bschcheckbox9);
//            BSCHLabel bschlabel12 = new BSCHLabel();
//            bschlabel12.setName("L-QTDTERM-1");
//            bschlabel12.setText("");
//            bschlabel12.setDimensions("371,313,0,11");
//            bschlabel12.setBehaviour("RDONLY");
//            panelPadre.add(bschlabel12);
//            BSCHButtonTextField bschbuttontextfield1 = new BSCHButtonTextField();
//            bschbuttontextfield1.setName("QTDTERM-1");
//            bschbuttontextfield1.setClickProcess("com.ibm.bsch.client.launcher.ModalWindowOperation");
//            bschbuttontextfield1.setClickProcessData("BRBW479,BANCO*CCC(1-4),AGENCIA*CCC(5-8),CONTA*CCC(9-20),TPCONSU*TIPPESQ");
//            bschbuttontextfield1.setDataName("QTETERM");
//            bschbuttontextfield1.setType("NUMERIC");
//            bschbuttontextfield1.setBehaviour("RDONLY");
//            bschbuttontextfield1.setDimensions("371,328,74,16");
//            bschbuttontextfield1.setMaxChars("3");
//            panelPadre.add(bschbuttontextfield1);
//            BSCHCheckBox bschcheckbox10 = new BSCHCheckBox();
//            bschcheckbox10.setName("CHKPROS-1");
//            bschcheckbox10.setDataName("CHKPROS");
//            bschcheckbox10.setDimensions("26,159,13,14");
//            panelPadre.add(bschcheckbox10);
//            BSCHLabel bschlabel13 = new BSCHLabel();
//            bschlabel13.setName("L-NOMPROS-1");
//            bschlabel13.setText("");
//            bschlabel13.setDimensions("43,145,0,15");
//            bschlabel13.setBehaviour("RDONLY");
//            panelPadre.add(bschlabel13);
//            BSCHTextField bschtextfield10 = new BSCHTextField();
//            bschtextfield10.setName("NOMPROS-1");
//            bschtextfield10.setDataName("NOMPROS");
//            bschtextfield10.setBehaviour("RDONLY");
//            bschtextfield10.setType("ALPHANUMERIC");
//            bschtextfield10.setMaxChars(80);
//            bschtextfield10.setDimensions("43,160,400,16");
//            panelPadre.add(bschtextfield10);
//            BSCHButton bschbutton1 = new BSCHButton();
//            bschbutton1.setName("PESC-1");
//            bschbutton1.setBehaviour("RDONLY");
//            bschbutton1.setDimensions("338,58,100,21");
//            bschbutton1.setText("Pesquisa");
//            panelPadre.add(bschbutton1);
//            BSCHButton bschbutton2 = new BSCHButton();
//            bschbutton2.setName("NOVAPESC-2");
//            bschbutton2.setClickProcess("com.ibm.bsch.client.launcher.ResetPanel");
//            bschbutton2.setClickProcess("com.ibm.bsch.client.launcher.LauncherCrossRelationByName");
//            bschbutton2.setClickProcessData("Relation31,Relation44,Relation45");
//            bschbutton2.setDimensions("338,67,100,21");
//            bschbutton2.setText("Nova pesquisa");
//            bschbutton2.setVisible(false);
//            panelPadre.add(bschbutton2);
//            BSCHButton bschbutton3 = new BSCHButton();
//            bschbutton3.setName("NA-IMPRIMIR-1");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.ExecuteTransaction");
//            bschbutton3.setClickProcessData("BWC3,BCODENT*CCC(1-4),BCODOFI*CCC(5-8),BNUMCON*CCC(9-20),IMPRCCB*'S',INDTIPO*'C',CODACAO*TIPPESQ,INCCBCE*CCBPAC");
//            bschbutton3.setClickProcessOutData("ALL,TFCANAL*CAMPADM(26-28),CTACOMB*TARIFA(4-1)[0],PACTAR*TARIFA,CAMP125(1-1),CMPDOCP,MAXEXTE*MAXSEGU,SORTEXT*VLRSORT,errores,MAILFAT(70-70),MAILFAT(1-69),CDCIDT11(3-1)[0]*CDCIDT1(1-3),CDCIDT12(3-1)[0]*CDCIDT1(4-6),CDCIDT13(3-1)[0]*CDCIDT1(7-9),CDCIDT21(3-1)[0]*CDCIDT2(1-3),CDCIDT22(3-1)[0]*CDCIDT2(4-6),CDCIDT23(3-1)[0]*CDCIDT2(7-9),CDDOMT1(3-1)[0]*CDDOMT1,TIPFOT1(3-1)[0]*TIPFOT1,CDDOMT2(3-1)[0]*CDDOMT2,TIPFOT2(3-1)[0]*TIPFOT2");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.ExecuteTransaction");
//            bschbutton3.setClickProcessParameters("LIST,PAGINATION,CONDITION=CHKPROS;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;TRUE");
//            bschbutton3.setClickProcessData("BWC5,CODENTI*CCC(1-4),CODAGEN*CCC(5-8),NUCONTA*CCC(9-20),TIPCONT*'C'");
//            bschbutton3.setClickProcessOutData("listDataTABLA3*listDataBWC5");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherCrossRelationByName");
//            bschbutton3.setClickProcessParameters("CONDITION=BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true");
//            bschbutton3.setClickProcessData("Relation10,Relation11,Relation42,Relation43");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##CHKPAC;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMPAC,ALL,DTNASC*CAMPO04(9-10)+CAMPO04(6-7)+CAMPO04(1-4),CODBAR*CAMPADM(21-24)+CAMPADM(1-20),CMPDOCP,MAILFAT(70-70),MAILFAT(1-69)");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##CHKPAC;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMPAC");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKPROS;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;TRUE");
//            bschbutton3.setClickProcessData("*FRMPROS,BRANCO*' ',listDataTABLA3");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKPROS;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;TRUE");
//            bschbutton3.setClickProcessData("*FRMPROS");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKCCB1;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true");
//            bschbutton3.setClickProcessData("*FRMCCB1,ALL,DIAMISS*DTEMISS(1-2),MESMISS*DTEMISS(4-5),ANOMISS*DTEMISS(7-10)");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKCCB1;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true");
//            bschbutton3.setClickProcessData("*FRMCCB1");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKCCB2;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true");
//            bschbutton3.setClickProcessData("*FRMCCB2,ALL,DIAMISS*DTEMISS(1-2),MESMISS*DTEMISS(4-5),ANOMISS*DTEMISS(7-10)");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKCCB2;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true");
//            bschbutton3.setClickProcessData("*FRMCCB2");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKCCB3;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true");
//            bschbutton3.setClickProcessData("*FRMCCB3,ALL,DIAMISS*DTEMISS(1-2),MESMISS*DTEMISS(4-5),ANOMISS*DTEMISS(7-10)");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKCCB3;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true");
//            bschbutton3.setClickProcessData("*FRMCCB3");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKCCB4;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMCCB4,ALL,DIAMISS*DTEMISS(1-2),MESMISS*DTEMISS(4-5),ANOMISS*DTEMISS(7-10)");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKCCB4;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMCCB4");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.ExecuteTransaction");
//            bschbutton3.setClickProcessParameters("LIST(JXM0BPS),PAGINATION,CONDITION=CHKTPCT;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##CTAPROP-2;SELECTED;BOOLEAN;EQ;VALUE;true");
//            bschbutton3.setClickProcessData("JXBP,TPTERMO*'A',ENTIDA*CCC(1-4),CENTRO*CCC(5-8),CUENTA*CCC(9-20),CDTAR*TARIFA,CDPROD*PRODUTO,CDSUBPR*SUBPROD,CDBARRA*CAMPADM(21-24)+DESMOD(1-12),IDABERT*'S',CDPABA*DEPEND3(1-4),IDMOVSA*MANCONM,NMCLI1A*CAMPO02,NRCPF1A*CAMPO03(23-42),NMCLI2A*CAMPO33,NRCPF2A*CAMPO34(23-42),DTDEBIA*DIADEBT,CDOPERA*CAMP126(1-3),CDDDDA*CAMP126(4-5),NRFONEA*CAMP126(6-14),TPPLANA*CAMP126(16-16),IDPRITA*CAMP126(17-17),TPPES1A*CAMPO03(3-4),CDBARRA*CAMPADM(21-24)+DESMOD(1-12),INDFOPA*CAMP125(1-1),CDAGPAB*AGSELEC,VLRMIN*VLINVES,DATALIM*PZINVES,PACDEST*PACMIGR");
//            bschbutton3.setClickProcessOutData("ALL,listDataTABLA2*listDataJXBP");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.ExecuteTransaction");
//            bschbutton3.setClickProcessParameters("LIST(JXM0BPS),PAGINATION,CONDITION=CHKTPCT;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##CTAABER-1;SELECTED;BOOLEAN;EQ;VALUE;true");
//            bschbutton3.setClickProcessData("JXBP,TPTERMO*'A',ENTIDA*CCC(1-4),CENTRO*CCC(5-8),CUENTA*CCC(9-20),CDTAR*TARIFA,CDPROD*PRODUTO,CDSUBPR*SUBPROD,IDABERT*'N',INDFOPA*CAMP125(1-1),CDAGPAB*AGSELEC,VLRMIN*VLINVES,DATALIM*PZINVES,PACDEST*PACMIGR");
//            bschbutton3.setClickProcessOutData("ALL,listDataTABLA2*listDataJXBP");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.ExecuteTransaction");
//            bschbutton3.setClickProcessParameters("LIST(JXM0BPT),PAGINATION,CONDITION=IDQUAD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("JXBT,CDTAR*TARIFA");
//            bschbutton3.setClickProcessOutData("listDataTABLA1*listDataJXBT");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKTPCT;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;TRUE");
//            bschbutton3.setClickProcessData("*FRMTPCT,ALL,NRCPFC1(11-1)[0],listDataTABLA2,listDataTABLA1,TFCODTAR*TARIFA");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKTPCT;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;TRUE");
//            bschbutton3.setClickProcessData("*FRMTPCT");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.ExecuteTransaction");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKPROT;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("BW47,BCODENT*CCC(1-4),BCODOFI*CCC(5-8),BNUMCON*CCC(9-20),INDTIPO*'C'");
//            bschbutton3.setClickProcessOutData("ALL");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKPROT;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true");
//            bschbutton3.setClickProcessData("*FRMPROT,ALL,DIAMISS*DTEMISS(1-2),MESMISS*DTEMISS(4-5),ANOMISS*DTEMISS(7-10)");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKPROT;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true");
//            bschbutton3.setClickProcessData("*FRMPROT");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.ExecuteTransaction");
//            bschbutton3.setClickProcessParameters("CONDITION=PRODSER(1-1);CONTEXT;ALPHANUMERIC;EQ;VALUE;3");
//            bschbutton3.setClickProcessData("MPTZ,CODENT*CAMPADM(1-4),CDPROD*PRODCRT,CDSUBP*PRODSER(4-7),CODMAR*PRODSER(2-3),INDTIPT*GPACGRP(2-4),FUNCCAR*'M',CNVENDA*'100',PENUMPE");
//            bschbutton3.setClickProcessOutData("VLRMSCP,errores");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherCrossRelationByName");
//            bschbutton3.setClickProcessData("Relation38,Relation39");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;TRUE##CHKSCEP;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMSCEP,TELA*'BRBW471',LOCAL,DATAAT,CAMPO02,CAMPO03,CAMPO06,CAMPO05,CAMPO09,CAMPO23,BCODENT,BCODOFI,CAMPADM,BRANCO*'123',ENDTIT1,BNUMCON,CAMPO08,CAMPO04,CAMPO17,CCC,CAMPO20,CAMPO18");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;TRUE##CHKSCEP;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMSCEP");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.ExecuteTransaction");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKSCRT;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("BWC6,CODENTI*CCC(1-4),CDAGEN*CCC(5-8),CTCORR*CCC(9-20),INDTELA*'A'");
//            bschbutton3.setClickProcessOutData("CDAGEN,CTCORR,NOMET1,CPFT1,DOCT1,DTDCT1,OPEXP1,PROFT1,PROFT1,ENDT1,NUMT1,COMPT1,BAIRT1,MUNT1,UFT1,CEPT1,EMAT1,TELDT1,TELNT1,NOMET2,CPFT2,DOCT2,DTDCT2,OPEXP2,PROFT2,ENDT2,NUMT2,COMPT2,BAIRT2,MUNT2,UFT2,CEPT2,EMAT2,TELDT2,TELNT2,SEGCON,VLPRMEN,PCPROL,VLPROL,COBER1,VLCSM1,COBER2,VLCSM2,COBER3,VLCSM3,COBER4,VLCSM4,COBER5,VLCSM5,COBER6,VLCSM6,COBER7,VLCSM7,COBER8,VLCSM8,COBER9,VLCSM9,COBER10,VLCSM10,COBER11,VLCSM11,COBER12,VLCSM12,CT1PRO,CT1NUM,CT2PRO,CT2NUM,CT3PRO,CT3NUM,LOCAL,DATA,TELCT2,CELUT2,DSCOB1,DSCOB2,DSCOB3,DSCOB4,DSCOB5,DSCOB6,DSCOB7,DSCOB8,DSCOB9,DSCOB10,DSCOB11,DSCOB12,DSCOB13,DSCOB14,DSCOB15,VLCOB1,VLCOB2,VLCOB3,VLCOB4,VLCOB5,VLCOB6,VLCOB7,VLCOB8,VLCOB9,VLCOB10,VLCOB11,VLCOB12,VLCOB13,VLCOB14,VLCOB15,VLPRE1,VLPRE2,VLPRE3,VLPRE4,VLPRE5,VLPRE6,VLPRE7,VLPRE8,VLPRE9,VLPRE10,VLPRE11,VLPRE12,VLPRE13,VLPRE14,VLPRE15,VLPRMEN,VLPIOF,RAZSEST,CNPJEST,ENDERE,CMLENDE,BAIRRO,CEP,CIDADE,UF,DDDFONE,NRFONE,RZSOCS1,CNPJSG1,NREGSU1,CDRAMO1,DSRAMO1,CDPROD1,DSPROD1,NRPRSU1,RZSOCS2,CNPJSG2,NREGSU2,CDRAMO2,DSRAMO2,CDPROD2,DSPROD2,NRPRSU2,NRPROP,NRAPOLI,TELCT1,CELUT1,VLPRMTO,DTNASC,OPEXPA1,OPEXPA2,FRMPAGM");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;TRUE##CHKSCRT;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMSCRT,BRANCO*' ',CDAGEN,CTCORR,NOMET1,CPFT1,DOCT1,DTDCT1,OPEXP1,PROFT1,PROFT1,ENDT1,NUMT1,COMPT1,BAIRT1,MUNT1,UFT1,CEPT1,EMAT1,TELDT1,TELNT1,NOMET2,CPFT2,DOCT2,DTDCT2,OPEXP2,PROFT2,ENDT2,NUMT2,COMPT2,BAIRT2,MUNT2,UFT2,CEPT2,EMAT2,TELDT2,TELNT2,SEGCON,VLPRMEN,PCPROL,VLPROL,COBER1,VLCSM1,COBER2,VLCSM2,COBER3,VLCSM3,COBER4,VLCSM4,COBER5,VLCSM5,COBER6,VLCSM6,COBER7,VLCSM7,COBER8,VLCSM8,COBER9,VLCSM9,COBER10,VLCSM10,COBER11,VLCSM11,COBER12,VLCSM12,CT1PRO,CT1NUM,CT2PRO,CT2NUM,CT3PRO,CT3NUM,LOCAL,DATA,TELCT2,CELUT2,DSCOB1,DSCOB2,DSCOB3,DSCOB4,DSCOB5,DSCOB6,DSCOB7,DSCOB8,DSCOB9,DSCOB10,DSCOB11,DSCOB12,DSCOB13,DSCOB14,DSCOB15,VLCOB1,VLCOB2,VLCOB3,VLCOB4,VLCOB5,VLCOB6,VLCOB7,VLCOB8,VLCOB9,VLCOB10,VLCOB11,VLCOB12,VLCOB13,VLCOB14,VLCOB15,VLPRE1,VLPRE2,VLPRE3,VLPRE4,VLPRE5,VLPRE6,VLPRE7,VLPRE8,VLPRE9,VLPRE10,VLPRE11,VLPRE12,VLPRE13,VLPRE14,VLPRE15,VLPRMEN,VLPIOF,RAZSEST,CNPJEST,ENDERE,CMLENDE,BAIRRO,CEP,CIDADE,UF,DDDFONE,NRFONE,RZSOCS1,CNPJSG1,NREGSU1,CDRAMO1,DSRAMO1,CDPROD1,DSPROD1,NRPRSU1,RZSOCS2,CNPJSG2,NREGSU2,CDRAMO2,DSRAMO2,CDPROD2,DSPROD2,NRPRSU2,NRPROP,NRAPOLI,TELCT1,CELUT1,VLPRMTO,TELA*'BRBW471',CAMPO08,CAMPO04,CAMPO18,DTNASC,CAMPADM,CAMPO35,OPEXPA1,OPEXPA2,FRMPAGM");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;TRUE##CHKSCRT;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMSCRT");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.ExecuteTransaction");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true");
//            bschbutton3.setClickProcessData("BWA4,ENTIDAD*CCC(1-4),CENALTA*CCC(5-8),NRCONTA*CCC(9-20),CODPROP,PENUMPE,INDICE");
//            bschbutton3.setClickProcessOutData("ALL,INDPROX,CODFORM*CODFORM+INDICE,PENUPRO");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true");
//            bschbutton3.setClickProcessData("*CODFORM,ALL");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true");
//            bschbutton3.setClickProcessData("*CODFORM");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.ExecuteTransaction");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##INDPROX;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("BWA4,ENTIDAD*CCC(1-4),CENALTA*CCC(5-8),NRCONTA*CCC(9-20),CODPROP,PENUMPE*PENUPRO,INDICE");
//            bschbutton3.setClickProcessOutData("ALL,INDPROX,CODFORM*CODFORM+INDICE,PENUPRO");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##INDPROX;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*CODFORM,ALL");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##INDPROX;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*CODFORM");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.ExecuteTransaction");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##INDPROX;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("BWA4,ENTIDAD*CCC(1-4),CENALTA*CCC(5-8),NRCONTA*CCC(9-20),CODPROP,PENUMPE*PENUPRO,INDICE");
//            bschbutton3.setClickProcessOutData("ALL,INDPROX,CODFORM*CODFORM+INDICE,PENUPRO");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##INDPROX;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*CODFORM,ALL");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##INDPROX;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*CODFORM");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.ExecuteTransaction");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##INDPROX;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("BWA4,ENTIDAD*CCC(1-4),CENALTA*CCC(5-8),NRCONTA*CCC(9-20),CODPROP,PENUMPE*PENUPRO,INDICE");
//            bschbutton3.setClickProcessOutData("ALL,INDPROX,CODFORM*CODFORM+INDICE,PENUPRO");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##INDPROX;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*CODFORM,ALL");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##INDPROX;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*CODFORM");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.ExecuteTransaction");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##INDPROX;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("BWA4,ENTIDAD*CCC(1-4),CENALTA*CCC(5-8),NRCONTA*CCC(9-20),CODPROP,PENUMPE*PENUPRO,INDICE");
//            bschbutton3.setClickProcessOutData("ALL,INDPROX,CODFORM*CODFORM+INDICE,PENUPRO");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##INDPROX;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*CODFORM,ALL");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##INDPROX;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*CODFORM");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.ExecuteTransaction");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##INDPROX;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("BWA4,ENTIDAD*CCC(1-4),CENALTA*CCC(5-8),NRCONTA*CCC(9-20),CODPROP,PENUMPE*PENUPRO,INDICE");
//            bschbutton3.setClickProcessOutData("ALL,INDPROX,CODFORM*CODFORM+INDICE,PENUPRO");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##INDPROX;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*CODFORM,ALL");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##INDPROX;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*CODFORM");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.ExecuteTransaction");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##INDPROX;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("BWA4,ENTIDAD*CCC(1-4),CENALTA*CCC(5-8),NRCONTA*CCC(9-20),CODPROP,PENUMPE*PENUPRO,INDICE");
//            bschbutton3.setClickProcessOutData("ALL,INDPROX,CODFORM*CODFORM+INDICE,PENUPRO");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##INDPROX;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*CODFORM,ALL");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=INDPROX;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*CODFORM");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.ExecuteTransaction");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##INDPROX;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("BWA4,ENTIDAD*CCC(1-4),CENALTA*CCC(5-8),NRCONTA*CCC(9-20),CODPROP,PENUMPE*PENUPRO,INDICE");
//            bschbutton3.setClickProcessOutData("ALL,INDPROX,CODFORM*CODFORM+INDICE,PENUPRO");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##INDPROX;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*CODFORM,ALL");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##INDPROX;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*CODFORM");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##INDPROX;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*CODFORM,ALL");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##INDPROX;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*CODFORM");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.ExecuteTransaction");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##FRMTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;BRBWTTIE##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true");
//            bschbutton3.setClickProcessData("BWC4,CODENTI*CCC(1-4),CODAGEN*CCC(5-8),NUCONTA*CCC(9-20),TIPCONS*TIPPESQ,INDTELA*'BRBW4710'");
//            bschbutton3.setClickProcessOutData("ALL,FRMTRSF1*FRMTRSF+INDITT1,FRMTRSF2*FRMTRSF+INDITT2,FRMTRSF3*FRMTRSF+INDITT3,FRMTRSF4*FRMTRSF+INDITT4,FRMTRSF5*FRMTRSF+INDITT5,FRMTRSF6*FRMTRSF+INDITT6,FRMTRSF7*FRMTRSF+INDITT7,FRMTRSF8*FRMTRSF+INDITT8,FRMTRSF9*FRMTRSF+INDITT9,FRMTRSF10*FRMTRSF+INDITT0");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##IDIMTT1;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMTRSF1,BRANCO*'BRANCO',NOMETT*NOMETT1,CPFTT*CPFTT1,TDOCTT*TDOCTT1,NDOCTT*NDOCTT1,EMISTT*EMISTT1,CODUFTT*CODUFT1,DTEMITT*DTEMIT1,DTVENTT*DTVENT1,AGSALTT*ACSALT1(1-4),COSALTT*ACSALT1(5-16),INDINTTT*IDIMTT1,AGINTTT*ACINTT1(1-4),COINTTT*ACINTT1(5-16),TPINTTT*TPINTT1,INEXTTT*INEXTT1,NUBANTT*NUBANT1,NOBANTT*NOBANT1,AGEXTTT*ACEXTT1(1-4),COEXTTT*ACEXTT1(5-16),TPEXTTT*TPEXTT1,INDSUS,SANTT*ISANTT1,SUSINT,SUSEXT,ISUSBCO,LOCDATA,NUMDOCE*NUMDCE0,NOMDCE*NOMDCE0");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##IDIMTT1;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMTRSF1");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##IDIMTT2;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMTRSF2,BRANCO*'BRANCO',NOMETT*NOMETT2,CPFTT*CPFTT2,TDOCTT*TDOCTT2,NDOCTT*NDOCTT2,EMISTT*EMISTT2,CODUFTT*CODUFT2,DTEMITT*DTEMIT2,DTVENTT*DTVENT2,AGSALTT*ACSALT2(1-4),COSALTT*ACSALT2(5-16),INDINTTT*IDIMTT2,AGINTTT*ACINTT2(1-4),COINTTT*ACINTT2(5-16),TPINTTT*TPINTT2,INEXTTT*INEXTT2,NUBANTT*NUBANT2,NOBANTT*NOBANT2,AGEXTTT*ACEXTT2(1-4),COEXTTT*ACEXTT2(5-16),TPEXTTT*TPEXTT2,INDSUS,SANTT*ISANTT2,SUSINT,SUSEXT,ISUSBCO,LOCDATA,NUMDOCE*NUMDCE1,NOMDCE*NOMDCE1");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##IDIMTT2;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMTRSF2");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##IDIMTT3;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMTRSF3,BRANCO*'BRANCO',NOMETT*NOMETT3,CPFTT*CPFTT3,TDOCTT*TDOCTT3,NDOCTT*NDOCTT3,EMISTT*EMISTT3,CODUFTT*CODUFT3,DTEMITT*DTEMIT3,DTVENTT*DTVENT3,AGSALTT*ACSALT3(1-4),COSALTT*ACSALT3(5-16),INDINTTT*IDIMTT3,AGINTTT*ACINTT3(1-4),COINTTT*ACINTT3(5-16),TPINTTT*TPINTT3,INEXTTT*INEXTT3,NUBANTT*NUBANT3,NOBANTT*NOBANT3,AGEXTTT*ACEXTT3(1-4),COEXTTT*ACEXTT3(5-16),TPEXTTT*TPEXTT3,INDSUS,SANTT*ISANTT3,SUSINT,SUSEXT,ISUSBCO,LOCDATA,NUMDOCE*NUMDCE2,NOMDCE*NOMDCE2");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##IDIMTT3;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMTRSF3");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##IDIMTT4;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMTRSF4,BRANCO*'BRANCO',NOMETT*NOMETT4,CPFTT*CPFTT4,TDOCTT*TDOCTT4,NDOCTT*NDOCTT4,EMISTT*EMISTT4,CODUFTT*CODUFT4,DTEMITT*DTEMIT4,DTVENTT*DTVENT4,AGSALTT*ACSALT4(1-4),COSALTT*ACSALT4(5-16),INDINTTT*IDIMTT4,AGINTTT*ACINTT4(1-4),COINTTT*ACINTT4(5-16),TPINTTT*TPINTT4,INEXTTT*INEXTT4,NUBANTT*NUBANT4,NOBANTT*NOBANT4,AGEXTTT*ACEXTT4(1-4),COEXTTT*ACEXTT4(5-16),TPEXTTT*TPEXTT4,INDSUS,SANTT*ISANTT4,SUSINT,SUSEXT,ISUSBCO,LOCDATA,NUMDOCE*NUMDCE3,NOMDCE*NOMDCE3");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##IDIMTT4;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMTRSF4");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##IDIMTT5;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMTRSF5,BRANCO*'BRANCO',NOMETT*NOMETT5,CPFTT*CPFTT5,TDOCTT*TDOCTT5,NDOCTT*NDOCTT5,EMISTT*EMISTT5,CODUFTT*CODUFT5,DTEMITT*DTEMIT5,DTVENTT*DTVENT5,AGSALTT*ACSALT5(1-4),COSALTT*ACSALT5(5-16),INDINTTT*IDIMTT5,AGINTTT*ACINTT5(1-4),COINTTT*ACINTT5(5-16),TPINTTT*TPINTT5,INEXTTT*INEXTT5,NUBANTT*NUBANT5,NOBANTT*NOBANT5,AGEXTTT*ACEXTT5(1-4),COEXTTT*ACEXTT5(5-16),TPEXTTT*TPEXTT5,INDSUS,SANTT*ISANTT5,SUSINT,SUSEXT,ISUSBCO,LOCDATA,NUMDOCE*NUMDCE4,NOMDCE*NOMDCE4");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##IDIMTT5;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMTRSF5");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##IDIMTT6;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMTRSF6,BRANCO*'BRANCO',NOMETT*NOMETT6,CPFTT*CPFTT6,TDOCTT*TDOCTT6,NDOCTT*NDOCTT6,EMISTT*EMISTT6,CODUFTT*CODUFT6,DTEMITT*DTEMIT6,DTVENTT*DTVENT6,AGSALTT*ACSALT6(1-4),COSALTT*ACSALT6(5-16),INDINTTT*IDIMTT6,AGINTTT*ACINTT6(1-4),COINTTT*ACINTT6(5-16),TPINTTT*TPINTT6,INEXTTT*INEXTT6,NUBANTT*NUBANT6,NOBANTT*NOBANT6,AGEXTTT*ACEXTT6(1-4),COEXTTT*ACEXTT6(5-16),TPEXTTT*TPEXTT6,INDSUS,SANTT*ISANTT6,SUSINT,SUSEXT,ISUSBCO,LOCDATA,NUMDOCE*NUMDCE5,NOMDCE*NOMDCE5");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##IDIMTT6;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMTRSF6");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##IDIMTT7;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMTRSF7,BRANCO*'BRANCO',NOMETT*NOMETT7,CPFTT*CPFTT7,TDOCTT*TDOCTT7,NDOCTT*NDOCTT7,EMISTT*EMISTT7,CODUFTT*CODUFT7,DTEMITT*DTEMIT7,DTVENTT*DTVENT7,AGSALTT*ACSALT7(1-4),COSALTT*ACSALT7(5-16),INDINTTT*IDIMTT7,AGINTTT*ACINTT7(1-4),COINTTT*ACINTT7(5-16),TPINTTT*TPINTT7,INEXTTT*INEXTT7,NUBANTT*NUBANT7,NOBANTT*NOBANT7,AGEXTTT*ACEXTT7(1-4),COEXTTT*ACEXTT7(5-16),TPEXTTT*TPEXTT7,INDSUS,SANTT*ISANTT7,SUSINT,SUSEXT,ISUSBCO,LOCDATA,NUMDOCE*NUMDCE6,NOMDCE*NOMDCE6");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##IDIMTT7;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMTRSF7");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##IDIMTT8;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMTRSF8,NOMETT*NOMETT8,CPFTT*CPFTT8,TDOCTT*TDOCTT8,NDOCTT*NDOCTT8,EMISTT*EMISTT8,CODUFTT*CODUFT8,DTEMITT*DTEMIT8,DTVENTT*DTVENT8,AGSALTT*ACSALT8(1-4),COSALTT*ACSALT8(5-16),INDINTTT*IDIMTT8,AGINTTT*ACINTT8(1-4),COINTTT*ACINTT8(5-16),TPINTTT*TPINTT8,INEXTTT*INEXTT8,NUBANTT*NUBANT8,NOBANTT*NOBANT8,AGEXTTT*ACEXTT8(1-4),COEXTTT*ACEXTT8(5-16),TPEXTTT*TPEXTT8,INDSUS,SANTT*ISANTT8,SUSINT,SUSEXT,ISUSBCO,LOCDATA,NUMDOCE*NUMDCE7,NOMDCE*NOMDCE7");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##IDIMTT8;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMTRSF8");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##IDIMTT9;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMTRSF9,BRANCO*'BRANCO',NOMETT*NOMETT9,CPFTT*CPFTT9,TDOCTT*TDOCTT9,NDOCTT*NDOCTT9,EMISTT*EMISTT9,CODUFTT*CODUFT9,DTEMITT*DTEMIT9,DTVENTT*DTVENT9,AGSALTT*ACSALT9(1-4),COSALTT*ACSALT9(5-16),INDINTTT*IDIMTT9,AGINTTT*ACINTT9(1-4),COINTTT*ACINTT9(5-16),TPINTTT*TPINTT9,INEXTTT*INEXTT9,NUBANTT*NUBANT9,NOBANTT*NOBANT9,AGEXTTT*ACEXTT9(1-4),COEXTTT*ACEXTT9(5-16),TPEXTTT*TPEXTT9,INDSUS,SANTT*ISANTT9,SUSINT,SUSEXT,ISUSBCO,LOCDATA,NUMDOCE*NUMDCE8,NOMDCE*NOMDCE8");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##IDIMTT9;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMTRSF9");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##IDIMTT0;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMTRSF10,BRANCO*'BRANCO',NOMETT*NOMETT0,CPFTT*CPFTT0,TDOCTT*TDOCTT0,NDOCTT*NDOCTT0,EMISTT*EMISTT0,CODUFTT*CODUFT0,DTEMITT*DTEMIT0,DTVENTT*DTVENT0,AGSALTT*ACSALT0(1-4),COSALTT*ACSALT0(5-16),INDINTTT*IDIMTT0,AGINTTT*ACINTT0(1-4),COINTTT*ACINTT0(5-16),TPINTTT*TPINTT0,INEXTTT*INEXTT0,NUBANTT*NUBANT0,NOBANTT*NOBANT0,AGEXTTT*ACEXTT0(1-4),COEXTTT*ACEXTT0(5-16),TPEXTTT*TPEXTT0,INDSUS,SANTT*ISANTT0,SUSINT,SUSEXT,ISUSBCO,LOCDATA,NUMDOCE*NUMDCE9,NOMDCE*NOMDCE9");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##IDIMTT0;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*FRMTRSF10");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.ExecuteTransaction");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##FRMTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;BRBWTTSV");
//            bschbutton3.setClickProcessData("BWB5,ENTIDAD*CCC(1-4),CENALTA*CCC(5-8),CODCTA*CCC(9-20),CODPROP,CODENTR");
//            bschbutton3.setClickProcessOutData("INDPOP,AGENCIA,CONTA,NOME,CPF,TIPDOC,NUMDOC,ORGEMS,UF,DTEMIS,DTVENC,FORMUL,DOCEMP,NOMEMP");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##FRMTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;BRBWTTSV");
//            bschbutton3.setClickProcessData("*FRMTRSF,BRANCO*' ',INDPOP,AGENCIA,CONTA,NOME,CPF,TIPDOC,NUMDOC,ORGEMS,UF,DTEMIS,DTVENC,FORMUL,DOCEMP,NOMEMP");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##FRMTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;BRBWTTSV");
//            bschbutton3.setClickProcessData("*FRMTRSF");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.ExecuteTransaction");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKMPPF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##CTAPROP-2;SELECTED;BOOLEAN;EQ;VALUE;true");
//            bschbutton3.setClickProcessData("MPGK,PAN*NUPAN,USOCLIQ*'N',CDSISTE*'BW',NUMTRAN*'999'");
//            bschbutton3.setClickProcessOutData("ALL,CODFORM,INDFORM,PAN,AGCONTA(1-4),NRCTA(1-14),CONTRAT(1-12),CODCAM,INDSPR,VENCFAT,ENDCLI,NMCICAD,UFCLI,CEPCLIE,NOMECLI,CPFCNPJ,RGCLIEN,NMEMBO,FUNCRTO,INDSUPB,AGENCON,CONTRAT,CDCANAL,CDSISTE,AGLOCAL,CDTERMI,HRTRANS,SQTRANS,USERID,CDTRANS,CDBANCO,CDAGENC,COMPROV*COMPROV(9-20),ULTDIGI,USOCLIQ,NOMEPT(1-50),TPCARP1,ENDCOP1,CPF(21-40),NUMCPF*CPF(1-11),CITYP2(1-20),ENDCOP2,DTTRANSS*DTTRANS(1-2)+'/'+DTTRANS(3-4)+'/'+DTTRANS(5-8),NMCICADD*NMCICAD,DTTRANS,SPPRP1,SPPRP2,TPCARP2,NRCONTA,PAN2,NMMARC2,NMSUBP2,LIMCRE2,INDFAEM,ENDMAIL,CRTOAD1,CRTOAD2,VLRSPPR,INDSPR2,VLRSPP2,INDFAE2,BAND1*CAMPDES(1-10),NPRD1*CAMPDES(11-45),NSEG1*CAMPDES(46-46),VLSEG1*CAMPDES(47-64),NFAT1*CAMPDES(65-65),NVENCF1*CAMPDES(66-75),FATDEB1*CAMPDES(76-78),NFUNC1*CAMPDES(79-98),NLIM1*CAMPDES(99-116),BAND2*CAMP2DS(1-10),NPRD2*CAMP2DS(11-45),NSEG2*CAMP2DS(46-46),VLSEG2*CAMP2DS(47-64),NFAT2*CAMP2DS(65-65),NVENCF2*CAMP2DS(66-75),FATDEB2*CAMP2DS(76-78),NFUNC2*CAMP2DS(79-98),NLIM2*CAMP2DS(99-116),NMMARCA,ANO*DTTRANS(5-8),NMSUBP,NMCIASS,NMEMBO,NMEMBO2,ICEXPRS,NOMEPROD*PRODUTO");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.ExecuteTransaction");
//            bschbutton3.setClickProcessParameters("LIST(MPM7250),PAGINATION,CONDITION=BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##CHKMPPF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##CTAPROP-2;SELECTED;BOOLEAN;EQ;VALUE;true");
//            bschbutton3.setClickProcessData("MPQK,CODENT*'0033',NUMCPF*CPFCNPJ,NUMTRAM*'999',CENTALT*AGENCON,CUENTA*CONTRAT,NUMCPF*CPFCNPJ");
//            bschbutton3.setClickProcessOutData("listDataTABELA*listDataMPQK");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.ExecuteTransaction");
//            bschbutton3.setClickProcessParameters("CONDITION=CHKMPPF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##CTAABER-1;SELECTED;BOOLEAN;EQ;VALUE;true");
//            bschbutton3.setClickProcessData("MPGK,PAN*NUPAN,USOCLIQ*'N',CDSISTE*'BW',NUMTRAN*'001'");
//            bschbutton3.setClickProcessOutData("ALL,AGCONTA(1-4),NRCTA(1-14),CONTRAT(1-12),COMPROV*COMPROV(9-20),NOMEPT(1-50),CPF(21-40),NUMCPF*CPF(1-11),CITYP2(1-20),DTTRANSS*DTTRANS(1-2)+'/'+DTTRANS(3-4)+'/'+DTTRANS(5-8),NMCICADD*NMCICAD,BAND1*CAMPDES(1-10),NPRD1*CAMPDES(11-45),NSEG1*CAMPDES(46-46),VLSEG1*CAMPDES(47-64),NFAT1*CAMPDES(65-65),NVENCF1*CAMPDES(66-75),FATDEB1*CAMPDES(76-78),NFUNC1*CAMPDES(79-98),NLIM1*CAMPDES(99-116),BAND2*CAMP2DS(1-10),NPRD2*CAMP2DS(11-45),NSEG2*CAMP2DS(46-46),VLSEG2*CAMP2DS(47-64),NFAT2*CAMP2DS(65-65),NVENCF2*CAMP2DS(66-75),FATDEB2*CAMP2DS(76-78),NFUNC2*CAMP2DS(79-98),NLIM2*CAMP2DS(99-116),ANO*DTTRANS(5-8),NOMEPROD*PRODUTO");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.ExecuteTransaction");
//            bschbutton3.setClickProcessParameters("LIST(MPM7250),PAGINATION,CONDITION=BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##CHKMPPF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##CTAABER-1;SELECTED;BOOLEAN;EQ;VALUE;true");
//            bschbutton3.setClickProcessData("MPQK,CODENT*'0033',NUMCPF*CPFCNPJ,NUMTRAM*'001',CENTALT*AGENCON,CUENTA*CONTRAT,NUMCPF*CPFCNPJ");
//            bschbutton3.setClickProcessOutData("listDataTABELA*listDataMPQK");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##CHKMPPF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*NOMFORM,NOMECLI,CPFCNPJ,RGCLIEN,ENDCLI,NMCICAD,UFCLI,CEPCLIE,AGCONTA,NRCTA,CODCAM,NMMARCA,NMSUBP,INDSPR,VLRSPPR,INDFAEM,NMMARC2,NMSUBP2,INDSPR2,VLRSPP2,INDFAE2,BAND1,NPRD1,NSEG1,VLSEG1,NFAT1,NVENCF1,FATDEB1,NFUNC1,NLIM1,BAND2,NPRD2,NSEG2,VLSEG2,NFAT2,NVENCF2,FATDEB2,NFUNC2,NLIM2,listDataTABELA,DTTRANSS,CDCANAL,CDSISTE,ANO,AGLOCAL,CDTERMI,DTTRANS,SQTRANS,USERID,CDTRANS,CDBANCO,CDAGENC,COMPROV,ULTDIGI,NMCIASS,ICEXPRS,PAN,PAN2,NMEMBO,NMEMBO2,ALL,NOMEPROD");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##CHKMPPF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschbutton3.setClickProcessData("*NOMFORM");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherPrintScreen");
//            bschbutton3.setClickProcessParameters("CONDITION=BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##CHKMPPF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##NOMFORM;CONTEXT;ALPHANUMERIC;NE;VALUE;NULL");
//            bschbutton3.setClickProcessData("*NOMFORM,NOMECLI,CPFCNPJ,RGCLIEN,ENDCLI,NMCICAD,UFCLI,CEPCLIE,AGCONTA,NRCTA,CODCAM,NMMARCA,NMSUBP,INDSPR,VLRSPPR,INDFAEM,NMMARC2,NMSUBP2,INDSPR2,VLRSPP2,INDFAE2,BAND1,NPRD1,NSEG1,VLSEG1,NFAT1,NVENCF1,FATDEB1,NFUNC1,NLIM1,BAND2,NPRD2,NSEG2,VLSEG2,NFAT2,NVENCF2,FATDEB2,NFUNC2,NLIM2,listDataTABELA,DTTRANSS,CDCANAL,CDSISTE,ANO,AGLOCAL,CDTERMI,DTTRANS,SQTRANS,USERID,CDTRANS,CDBANCO,CDAGENC,COMPROV,ULTDIGI,NMCIASS,ICEXPRS,PAN,PAN2,NMEMBO,NMEMBO2,ALL,NOMEPROD");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherOpenDoc");
//            bschbutton3.setClickProcessParameters("PRINT_DOCGEN,CONDITION=BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##CHKMPPF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S##NOMFORM;CONTEXT;ALPHANUMERIC;NE;VALUE;NULL");
//            bschbutton3.setClickProcessData("*NOMFORM");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.ClosePanelAndHisProcesses");
//            bschbutton3.setClickProcessParameters("CONDITION=BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;true##BRBW471;PARENTWINDOW;ALPHANUMERIC;EQ;VALUE;BRBW002");
//            bschbutton3.setClickProcess("com.ibm.bsch.client.launcher.LauncherCrossRelationByName");
//            bschbutton3.setClickProcessData("Relation30");
//            bschbutton3.setBehaviour("RDONLY");
//            bschbutton3.setDimensions("242,432,100,21");
//            bschbutton3.setText("Imprimir");
//            bschbutton3.setIconFile("impresora habilitada.gif");
//            panelPadre.add(bschbutton3);
//            BSCHButton bschbutton4 = new BSCHButton();
//            bschbutton4.setName("ABANDONAR-1");
//            bschbutton4.setButtonType("CancelarIcon");
//            bschbutton4.setDimensions("348,432,100,21");
//            bschbutton4.setText("Cancelar");
//            panelPadre.add(bschbutton4);
//            BSCHLabel bschlabel14 = new BSCHLabel();
//            bschlabel14.setName("L-NOMTRSF-3");
//            bschlabel14.setText("");
//            bschlabel14.setDimensions("43,312,0,15");
//            bschlabel14.setBehaviour("RDONLY");
//            panelPadre.add(bschlabel14);
//            BSCHTextField bschtextfield11 = new BSCHTextField();
//            bschtextfield11.setName("NOMTRSF-3");
//            bschtextfield11.setDataName("NOMTRSF");
//            bschtextfield11.setBehaviour("RDONLY");
//            bschtextfield11.setType("ALPHANUMERIC");
//            bschtextfield11.setMaxChars(120);
//            bschtextfield11.setDimensions("43,327,319,16");
//            panelPadre.add(bschtextfield11);
//            BSCHCheckBox bschcheckbox11 = new BSCHCheckBox();
//            bschcheckbox11.setName("CHKSCEP-1");
//            bschcheckbox11.setDataName("CHKSCEP");
//            bschcheckbox11.setBehaviour("RDONLY");
//            bschcheckbox11.setDimensions("26,370,13,14");
//            panelPadre.add(bschcheckbox11);
//            BSCHLabel bschlabel15 = new BSCHLabel();
//            bschlabel15.setName("L-NOMSCEP-1");
//            bschlabel15.setText("");
//            bschlabel15.setDimensions("43,355,0,15");
//            bschlabel15.setBehaviour("RDONLY");
//            panelPadre.add(bschlabel15);
//            BSCHTextField bschtextfield12 = new BSCHTextField();
//            bschtextfield12.setName("NOMSCEP-1");
//            bschtextfield12.setDataName("NOMSCEP");
//            bschtextfield12.setBehaviour("RDONLY");
//            bschtextfield12.setType("ALPHANUMERIC");
//            bschtextfield12.setMaxChars(120);
//            bschtextfield12.setDimensions("43,370,399,16");
//            panelPadre.add(bschtextfield12);
//            BSCHCheckBox bschcheckbox12 = new BSCHCheckBox();
//            bschcheckbox12.setName("CHKSCRT-1");
//            bschcheckbox12.setDataName("CHKSCRT");
//            bschcheckbox12.setBehaviour("RDONLY");
//            bschcheckbox12.setDimensions("26,393,13,14");
//            panelPadre.add(bschcheckbox12);
//            BSCHLabel bschlabel16 = new BSCHLabel();
//            bschlabel16.setName("L-NOMSCRT-1");
//            bschlabel16.setText("");
//            bschlabel16.setDimensions("43,377,0,15");
//            bschlabel16.setBehaviour("RDONLY");
//            panelPadre.add(bschlabel16);
//            BSCHTextField bschtextfield13 = new BSCHTextField();
//            bschtextfield13.setName("NOMSCRT-1");
//            bschtextfield13.setDataName("NOMSCRT");
//            bschtextfield13.setBehaviour("RDONLY");
//            bschtextfield13.setType("ALPHANUMERIC");
//            bschtextfield13.setMaxChars(120);
//            bschtextfield13.setDimensions("43,392,399,16");
//            panelPadre.add(bschtextfield13);
//            BSCHLabel bschlabel17 = new BSCHLabel();
//            bschlabel17.setName("L-CODIGO-PROVEEDOR-1");
//            bschlabel17.setVisible(false);
//            bschlabel17.setText("");
//            bschlabel17.setDimensions("11,439,0,15");
//            bschlabel17.setBehaviour("OPT");
//            panelPadre.add(bschlabel17);
//            BSCHTextField bschtextfield14 = new BSCHTextField();
//            bschtextfield14.setName("CODIGO-PROVEEDOR-1");
//            bschtextfield14.setDataName("CPROVEED");
//            bschtextfield14.setType("ALPHANUMERIC");
//            bschtextfield14.setMaxChars(300);
//            bschtextfield14.setDimensions("11,454,56,16");
//            bschtextfield14.setVisible(false);
//            panelPadre.add(bschtextfield14);
//            BSCHCrossRelation bschcrossrelation = new BSCHCrossRelation();
//            bschcrossrelation.setName("Relation1");
//            bschcrossrelation.setCondition("BRBW471;PARENTWINDOW;ALPHANUMERIC;EQ;VALUE;BRBW002");
//            bschcrossrelation.setAction("CTAABER-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            bschcrossrelation.setAction("CTAPROP-2;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            bschcrossrelation.setAction("CCCPRO-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            bschcrossrelation.setAction("CCCABE-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            bschcrossrelation.setAction("NA-BUSCAR-1;VISIBLE;BOOLEAN;EQ;VALUE;FALSE");
//            bschcrossrelation.setAction("L-NA-BUSCAR-1;VISIBLE;BOOLEAN;EQ;VALUE;FALSE");
//            bschcrossrelation.setAction("NA-BUSCAR-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation.setAction("INDACAO;CONTEXT;ALPHANUMERIC;EQ;VALUE;PRE");
//            bschcrossrelation.setAction("PESC-1;VISIBLE;BOOLEAN;NE;VALUE;TRUE");
//            bschcrossrelation.setAction("L-PESC-1;VISIBLE;BOOLEAN;NE;VALUE;TRUE");
//            bschcrossrelation.setAction("NA-BUSCAR-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation.setAction("CTAABER-1;SELECTED;BOOLEAN;EQ;VALUE;FALSE");
//            bschcrossrelation.setAction("CTAPROP-2;SELECTED;BOOLEAN;EQ;VALUE;TRUE");
//            bschcrossrelation.setAction("CDSISTE;CONTEXT;ALPHANUMERIC;EQ;VALUE;BW");
//            panelPadre.add(bschcrossrelation);
//            BSCHCrossRelation bschcrossrelation1 = new BSCHCrossRelation();
//            bschcrossrelation1.setName("Relation2");
//            bschcrossrelation1.setCondition("BRBW471;PARENTWINDOW;ALPHANUMERIC;NE;VALUE;BRBW002");
//            bschcrossrelation1.setCondition("NA-BUSCAR-1;VISIBLE;BOOLEAN;EQ;VALUE;true");
//            bschcrossrelation1.setAction("INDACAO;CONTEXT;ALPHANUMERIC;EQ;VALUE;PES");
//            bschcrossrelation1.setAction("CTAABER-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation1.setAction("CTAPROP-2;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            panelPadre.add(bschcrossrelation1);
//            BSCHCrossRelation bschcrossrelation2 = new BSCHCrossRelation();
//            bschcrossrelation2.setName("Relation3");
//            bschcrossrelation2.setCondition("CHKPAC-1;SELECTED;BOOLEAN;EQ;VALUE;true||CHKCCB1-1;SELECTED;BOOLEAN;EQ;VALUE;true||CHKCCB2-1;SELECTED;BOOLEAN;EQ;VALUE;true||CHKTPCT-1;SELECTED;BOOLEAN;EQ;VALUE;true||CHKFHCD-1;SELECTED;BOOLEAN;EQ;VALUE;true||CHKPROT-1;SELECTED;BOOLEAN;EQ;VALUE;true||CHKTRSF-1;SELECTED;BOOLEAN;EQ;VALUE;true||CHKCCB3-1;SELECTED;BOOLEAN;EQ;VALUE;true||CHKCCB4-1;SELECTED;BOOLEAN;EQ;VALUE;true||CHKMPPF-2;SELECTED;BOOLEAN;EQ;VALUE;true||CHKPROS-1;SELECTED;BOOLEAN;EQ;VALUE;true||CHKSCEP-1;SELECTED;BOOLEAN;EQ;VALUE;true||CHKSCRT-1;SELECTED;BOOLEAN;EQ;VALUE;true");
//            bschcrossrelation2.setAction("NA-IMPRIMIR-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation2.setElseAction("NA-IMPRIMIR-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            panelPadre.add(bschcrossrelation2);
//            BSCHCrossRelation bschcrossrelation3 = new BSCHCrossRelation();
//            bschcrossrelation3.setName("Relation4");
//            bschcrossrelation3.setCondition("CTAPOUP;CONTEXT;ALPHANUMERIC;NE;VALUE;NULL");
//            bschcrossrelation3.setAction("TFCTAPOUP;CONTEXT;ALPHANUMERIC;EQ;TFENTIDAD+AGPOUP+CTAPOUP;CONTEXT");
//            bschcrossrelation3.setElseAction("TFCTAPOUP;CONTEXT;ALPHANUMERIC;EQ;VALUE;NULL");
//            panelPadre.add(bschcrossrelation3);
//            BSCHCrossRelation bschcrossrelation4 = new BSCHCrossRelation();
//            bschcrossrelation4.setName("Relation5");
//            bschcrossrelation4.setCondition("ENVTALN;CONTEXT;ALPHANUMERIC;EQ;VALUE;NULL");
//            bschcrossrelation4.setAction("TFENVTALN;CONTEXT;ALPHANUMERIC;EQ;VALUE;N");
//            bschcrossrelation4.setElseAction("TFENVTALN;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            panelPadre.add(bschcrossrelation4);
//            BSCHCrossRelation bschcrossrelation5 = new BSCHCrossRelation();
//            bschcrossrelation5.setName("Relation6");
//            bschcrossrelation5.setCondition("DOCAPT1(23-32);CONTEXT;ALPHANUMERIC;EQ;VALUE;0001-01-01");
//            bschcrossrelation5.setAction("DOCAPT1(23-32);CONTEXT;ALPHANUMERIC;EQ;VALUE;NULL");
//            panelPadre.add(bschcrossrelation5);
//            BSCHCrossRelation bschcrossrelation6 = new BSCHCrossRelation();
//            bschcrossrelation6.setName("Relation7");
//            bschcrossrelation6.setCondition("SUBPROD;CONTEXT;ALPHANUMERIC;NE;VALUE;NULL");
//            bschcrossrelation6.setAction("DSUBPROD;CONTEXT;ALPHANUMERIC;EQ;PRODUTO+SUBPROD;CONTEXT");
//            panelPadre.add(bschcrossrelation6);
//            BSCHCrossRelation bschcrossrelation7 = new BSCHCrossRelation();
//            bschcrossrelation7.setName("Relation8");
//            bschcrossrelation7.setCondition("CAMPO09;CONTEXT;ALPHANUMERIC;NE;VALUE;NULL");
//            bschcrossrelation7.setAction("CAMPO091010;CONTEXT;ALPHANUMERIC;EQ;'00'+CAMPO09(10-10);CONTEXT");
//            bschcrossrelation7.setElseAction("CAMPO091010;CONTEXT;ALPHANUMERIC;EQ;VALUE;NULL");
//            panelPadre.add(bschcrossrelation7);
//            BSCHCrossRelation bschcrossrelation8 = new BSCHCrossRelation();
//            bschcrossrelation8.setName("Relation9");
//            bschcrossrelation8.setCondition("CAMPO40;CONTEXT;ALPHANUMERIC;NE;VALUE;NULL");
//            bschcrossrelation8.setAction("CAMPO401010;CONTEXT;ALPHANUMERIC;EQ;'00'+CAMPO40(10-10);CONTEXT");
//            bschcrossrelation8.setElseAction("CAMPO401010;CONTEXT;ALPHANUMERIC;EQ;VALUE;NULL");
//            panelPadre.add(bschcrossrelation8);
//            BSCHCrossRelation bschcrossrelation9 = new BSCHCrossRelation();
//            bschcrossrelation9.setName("Relation10");
//            bschcrossrelation9.setCondition("CAMPO17;CONTEXT;ALPHANUMERIC;NE;VALUE;NULL");
//            bschcrossrelation9.setAction("UFCOM;CONTEXT;ALPHANUMERIC;EQ;CAMPO17(1-2);CONTEXT");
//            bschcrossrelation9.setAction("CIDADECOM;CONTEXT;ALPHANUMERIC;EQ;CAMPO17(3-9);CONTEXT");
//            panelPadre.add(bschcrossrelation9);
//            BSCHCrossRelation bschcrossrelation10 = new BSCHCrossRelation();
//            bschcrossrelation10.setName("Relation11");
//            bschcrossrelation10.setCondition("CAMP132;CONTEXT;ALPHANUMERIC;NE;VALUE;NULL");
//            bschcrossrelation10.setAction("CIDADEALT;CONTEXT;ALPHANUMERIC;EQ;CAMP132(1-7);CONTEXT");
//            panelPadre.add(bschcrossrelation10);
//            BSCHCrossRelation bschcrossrelation11 = new BSCHCrossRelation();
//            bschcrossrelation11.setName("Relation12");
//            bschcrossrelation11.setCondition("CAMPO40;CONTEXT;ALPHANUMERIC;NE;VALUE;NULL");
//            bschcrossrelation11.setAction("UFRES2;CONTEXT;ALPHANUMERIC;EQ;CAMPO40(1-2);CONTEXT");
//            bschcrossrelation11.setAction("CIDADERES2;CONTEXT;ALPHANUMERIC;EQ;CAMPO40(3-9);CONTEXT");
//            bschcrossrelation11.setElseAction("UFRES2;CONTEXT;ALPHANUMERIC;EQ;VALUE;NULL");
//            bschcrossrelation11.setElseAction("CIDADERES2;CONTEXT;ALPHANUMERIC;EQ;VALUE;NULL");
//            panelPadre.add(bschcrossrelation11);
//            BSCHCrossRelation bschcrossrelation12 = new BSCHCrossRelation();
//            bschcrossrelation12.setName("Relation13");
//            bschcrossrelation12.setCondition("CAMPO48;CONTEXT;ALPHANUMERIC;NE;VALUE;NULL");
//            bschcrossrelation12.setAction("UFCOM2;CONTEXT;ALPHANUMERIC;EQ;CAMPO48(1-2);CONTEXT");
//            bschcrossrelation12.setAction("CIDADECOM2;CONTEXT;ALPHANUMERIC;EQ;CAMPO48(3-9);CONTEXT");
//            bschcrossrelation12.setElseAction("UFCOM2;CONTEXT;ALPHANUMERIC;EQ;VALUE;NULL");
//            bschcrossrelation12.setElseAction("CIDADECOM2;CONTEXT;ALPHANUMERIC;EQ;VALUE;NULL");
//            panelPadre.add(bschcrossrelation12);
//            BSCHCrossRelation bschcrossrelation13 = new BSCHCrossRelation();
//            bschcrossrelation13.setName("Relation14");
//            bschcrossrelation13.setCondition("TIPPESQ;CONTEXT;ALPHANUMERIC;EQ;VALUE;P");
//            bschcrossrelation13.setAction("CTAPROP-2;SELECTED;BOOLEAN;EQ;VALUE;true");
//            bschcrossrelation13.setElseAction("CTAABER-1;SELECTED;BOOLEAN;EQ;VALUE;true");
//            panelPadre.add(bschcrossrelation13);
//            BSCHCrossRelation bschcrossrelation14 = new BSCHCrossRelation();
//            bschcrossrelation14.setName("Relation15");
//            bschcrossrelation14.setCondition("CTAABER-1;SELECTED;BOOLEAN;EQ;VALUE;TRUE");
//            bschcrossrelation14.setCondition("BRBW471;PARENTWINDOW;ALPHANUMERIC;NE;VALUE;BRBW002");
//            bschcrossrelation14.setAction("TIPPESQ;CONTEXT;ALPHANUMERIC;EQ;VALUE;A");
//            bschcrossrelation14.setAction("CDSISTE;CONTEXT;ALPHANUMERIC;EQ;VALUE;MP");
//            bschcrossrelation14.setAction("CCCPRO-1;VISIBLE;BOOLEAN;EQ;VALUE;FALSE");
//            bschcrossrelation14.setAction("L-CCCPRO-1;VISIBLE;BOOLEAN;EQ;VALUE;FALSE");
//            bschcrossrelation14.setAction("CCCPRO-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation14.setAction("CCCABE-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;IREQ");
//            bschcrossrelation14.setAction("CCCABE-1;VISIBLE;BOOLEAN;EQ;VALUE;TRUE");
//            bschcrossrelation14.setAction("L-CCCABE-1;VISIBLE;BOOLEAN;EQ;VALUE;TRUE");
//            panelPadre.add(bschcrossrelation14);
//            BSCHCrossRelation bschcrossrelation15 = new BSCHCrossRelation();
//            bschcrossrelation15.setName("Relation16");
//            bschcrossrelation15.setCondition("CTAPROP-2;SELECTED;BOOLEAN;EQ;VALUE;TRUE");
//            bschcrossrelation15.setCondition("BRBW471;PARENTWINDOW;ALPHANUMERIC;NE;VALUE;BRBW002");
//            bschcrossrelation15.setAction("TIPPESQ;CONTEXT;ALPHANUMERIC;EQ;VALUE;P");
//            bschcrossrelation15.setAction("CDSISTE;CONTEXT;ALPHANUMERIC;EQ;VALUE;BW");
//            bschcrossrelation15.setAction("CCCPRO-1;VISIBLE;BOOLEAN;EQ;VALUE;true");
//            bschcrossrelation15.setAction("L-CCCPRO-1;VISIBLE;BOOLEAN;EQ;VALUE;true");
//            bschcrossrelation15.setAction("CCCPRO-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;IREQ");
//            bschcrossrelation15.setAction("CCCABE-1;VISIBLE;BOOLEAN;EQ;VALUE;FALSE");
//            bschcrossrelation15.setAction("L-CCCABE-1;VISIBLE;BOOLEAN;EQ;VALUE;FALSE");
//            bschcrossrelation15.setAction("CCCABE-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            panelPadre.add(bschcrossrelation15);
//            BSCHCrossRelation bschcrossrelation16 = new BSCHCrossRelation();
//            bschcrossrelation16.setName("Relation17");
//            bschcrossrelation16.setCondition("INDPAC;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschcrossrelation16.setAction("CHKPAC-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation16.setElseAction("CHKPAC-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            panelPadre.add(bschcrossrelation16);
//            BSCHCrossRelation bschcrossrelation17 = new BSCHCrossRelation();
//            bschcrossrelation17.setName("Relation18");
//            bschcrossrelation17.setCondition("INDCCB1;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschcrossrelation17.setAction("CHKCCB1-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation17.setElseAction("CHKCCB1-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            panelPadre.add(bschcrossrelation17);
//            BSCHCrossRelation bschcrossrelation18 = new BSCHCrossRelation();
//            bschcrossrelation18.setName("Relation19");
//            bschcrossrelation18.setCondition("INDCCB2;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschcrossrelation18.setAction("CHKCCB2-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation18.setElseAction("CHKCCB2-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            panelPadre.add(bschcrossrelation18);
//            BSCHCrossRelation bschcrossrelation19 = new BSCHCrossRelation();
//            bschcrossrelation19.setName("Relation20");
//            bschcrossrelation19.setCondition("INDTPCT;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschcrossrelation19.setAction("CHKTPCT-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation19.setElseAction("CHKTPCT-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            panelPadre.add(bschcrossrelation19);
//            BSCHCrossRelation bschcrossrelation20 = new BSCHCrossRelation();
//            bschcrossrelation20.setName("Relation21");
//            bschcrossrelation20.setCondition("INDPROT;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschcrossrelation20.setAction("CHKPROT-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation20.setElseAction("CHKPROT-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            panelPadre.add(bschcrossrelation20);
//            BSCHCrossRelation bschcrossrelation21 = new BSCHCrossRelation();
//            bschcrossrelation21.setName("Relation22");
//            bschcrossrelation21.setCondition("INDDOSS;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschcrossrelation21.setAction("CHKDOSS;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation21.setElseAction("CHKDOSS;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            panelPadre.add(bschcrossrelation21);
//            BSCHCrossRelation bschcrossrelation22 = new BSCHCrossRelation();
//            bschcrossrelation22.setName("Relation23");
//            bschcrossrelation22.setCondition("INDFHCD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschcrossrelation22.setAction("CHKFHCD-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation22.setElseAction("CHKFHCD-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            panelPadre.add(bschcrossrelation22);
//            BSCHCrossRelation bschcrossrelation23 = new BSCHCrossRelation();
//            bschcrossrelation23.setName("Relation24");
//            bschcrossrelation23.setCondition("CHKFHCD-1;SELECTED;BOOLEAN;EQ;VALUE;true");
//            bschcrossrelation23.setCondition("TFMENU;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschcrossrelation23.setAction("REPRES-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;IREQ");
//            panelPadre.add(bschcrossrelation23);
//            BSCHCrossRelation bschcrossrelation24 = new BSCHCrossRelation();
//            bschcrossrelation24.setName("Relation25");
//            bschcrossrelation24.setCondition("CHKFHCD-1;SELECTED;BOOLEAN;EQ;VALUE;false");
//            bschcrossrelation24.setAction("REPRES-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            panelPadre.add(bschcrossrelation24);
//            BSCHCrossRelation bschcrossrelation25 = new BSCHCrossRelation();
//            bschcrossrelation25.setName("Relation26");
//            bschcrossrelation25.setCondition("INDTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschcrossrelation25.setAction("CHKTRSF-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation25.setElseAction("CHKTRSF-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            panelPadre.add(bschcrossrelation25);
//            BSCHCrossRelation bschcrossrelation26 = new BSCHCrossRelation();
//            bschcrossrelation26.setName("Relation27");
//            bschcrossrelation26.setCondition("INDCCB3;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschcrossrelation26.setAction("CHKCCB3-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation26.setElseAction("CHKCCB3-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            panelPadre.add(bschcrossrelation26);
//            BSCHCrossRelation bschcrossrelation27 = new BSCHCrossRelation();
//            bschcrossrelation27.setName("Relation28");
//            bschcrossrelation27.setCondition("TFMENU;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschcrossrelation27.setCondition("CTAABER-1;SELECTED;BOOLEAN;EQ;VALUE;true");
//            bschcrossrelation27.setAction("CCCABE-1;VISIBLE;BOOLEAN;EQ;VALUE;TRUE");
//            bschcrossrelation27.setAction("L-CCCABE-1;VISIBLE;BOOLEAN;EQ;VALUE;TRUE");
//            bschcrossrelation27.setAction("CCCABE-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;IREQ");
//            bschcrossrelation27.setAction("CCCPRO-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            bschcrossrelation27.setAction("CCCPRO-1;VISIBLE;BOOLEAN;EQ;VALUE;FALSE");
//            bschcrossrelation27.setAction("L-CCCPRO-1;VISIBLE;BOOLEAN;EQ;VALUE;FALSE");
//            bschcrossrelation27.setAction("CCCPRO-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation27.setAction("CODACAO;CONTEXT;ALPHANUMERIC;EQ;VALUE;A");
//            panelPadre.add(bschcrossrelation27);
//            BSCHCrossRelation bschcrossrelation28 = new BSCHCrossRelation();
//            bschcrossrelation28.setName("Relation29");
//            bschcrossrelation28.setCondition("TFMENU;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschcrossrelation28.setCondition("CTAPROP-2;SELECTED;BOOLEAN;EQ;VALUE;true");
//            bschcrossrelation28.setAction("CCCABE-1;VISIBLE;BOOLEAN;EQ;VALUE;FALSE");
//            bschcrossrelation28.setAction("L-CCCABE-1;VISIBLE;BOOLEAN;EQ;VALUE;FALSE");
//            bschcrossrelation28.setAction("CCCABE-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation28.setAction("CCCPRO-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;IREQ");
//            bschcrossrelation28.setAction("CCCPRO-1;VISIBLE;BOOLEAN;EQ;VALUE;TRUE");
//            bschcrossrelation28.setAction("L-CCCPRO-1;VISIBLE;BOOLEAN;EQ;VALUE;TRUE");
//            bschcrossrelation28.setAction("CODACAO;CONTEXT;ALPHANUMERIC;EQ;VALUE;P");
//            panelPadre.add(bschcrossrelation28);
//            BSCHCrossRelation bschcrossrelation29 = new BSCHCrossRelation();
//            bschcrossrelation29.setName("Relation30");
//            bschcrossrelation29.setCondition("NA-BUSCAR-1;ISCLICKED;BOOLEAN;EQ;VALUE;true||NA-IMPRIMIR-1;ISCLICKED;BOOLEAN;EQ;VALUE;true");
//            bschcrossrelation29.setAction("NOVAPESC-2;VISIBLE;BOOLEAN;EQ;VALUE;TRUE");
//            bschcrossrelation29.setAction("L-NOVAPESC-2;VISIBLE;BOOLEAN;EQ;VALUE;TRUE");
//            bschcrossrelation29.setAction("NA-BUSCAR-1;VISIBLE;BOOLEAN;EQ;VALUE;FALSE");
//            bschcrossrelation29.setAction("L-NA-BUSCAR-1;VISIBLE;BOOLEAN;EQ;VALUE;FALSE");
//            bschcrossrelation29.setAction("NA-BUSCAR-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation29.setAction("PESC-1;VISIBLE;BOOLEAN;EQ;VALUE;FALSE");
//            bschcrossrelation29.setAction("L-PESC-1;VISIBLE;BOOLEAN;EQ;VALUE;FALSE");
//            bschcrossrelation29.setAction("PESC-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation29.setAction("NA-BUSCAR-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            bschcrossrelation29.setAction("CTAABER-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            bschcrossrelation29.setAction("CTAPROP-2;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            bschcrossrelation29.setAction("CCCABE-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            bschcrossrelation29.setAction("CCCPRO-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            panelPadre.add(bschcrossrelation29);
//            BSCHCrossRelation bschcrossrelation30 = new BSCHCrossRelation();
//            bschcrossrelation30.setName("Relation31");
//            bschcrossrelation30.setCondition("NOVAPESC-2;ISCLICKED;BOOLEAN;EQ;VALUE;TRUE");
//            bschcrossrelation30.setAction("NOVAPESC-2;VISIBLE;BOOLEAN;EQ;VALUE;false");
//            bschcrossrelation30.setAction("L-NOVAPESC-2;VISIBLE;BOOLEAN;EQ;VALUE;false");
//            bschcrossrelation30.setAction("NOVAPESC-2;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation30.setAction("NA-BUSCAR-1;VISIBLE;BOOLEAN;EQ;VALUE;true");
//            bschcrossrelation30.setAction("L-NA-BUSCAR-1;VISIBLE;BOOLEAN;EQ;VALUE;true");
//            bschcrossrelation30.setAction("PESC-1;VISIBLE;BOOLEAN;EQ;VALUE;false");
//            bschcrossrelation30.setAction("L-PESC-1;VISIBLE;BOOLEAN;EQ;VALUE;false");
//            bschcrossrelation30.setAction("PESC-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation30.setAction("CHKPAC-1;SELECTED;BOOLEAN;EQ;VALUE;false");
//            bschcrossrelation30.setAction("CHKCCB1-1;SELECTED;BOOLEAN;EQ;VALUE;false");
//            bschcrossrelation30.setAction("CHKCCB2-1;SELECTED;BOOLEAN;EQ;VALUE;false");
//            bschcrossrelation30.setAction("CHKTPCT-1;SELECTED;BOOLEAN;EQ;VALUE;false");
//            bschcrossrelation30.setAction("CHKFHCD-1;SELECTED;BOOLEAN;EQ;VALUE;false");
//            bschcrossrelation30.setAction("CHKPROT-1;SELECTED;BOOLEAN;EQ;VALUE;false");
//            bschcrossrelation30.setAction("CHKDOSS-1;SELECTED;BOOLEAN;EQ;VALUE;false");
//            bschcrossrelation30.setAction("CHKTRSF-1;SELECTED;BOOLEAN;EQ;VALUE;false");
//            bschcrossrelation30.setAction("CHKCCB3-1;SELECTED;BOOLEAN;EQ;VALUE;false");
//            bschcrossrelation30.setAction("CHKCCB4-1;SELECTED;BOOLEAN;EQ;VALUE;false");
//            bschcrossrelation30.setAction("CHKMPPF-2;SELECTED;BOOLEAN;EQ;VALUE;false");
//            bschcrossrelation30.setAction("CHKPAC-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            bschcrossrelation30.setAction("CHKCCB1-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            bschcrossrelation30.setAction("CHKCCB2-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            bschcrossrelation30.setAction("CHKTPCT-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            bschcrossrelation30.setAction("CHKFHCD-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            bschcrossrelation30.setAction("CHKPROT-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            bschcrossrelation30.setAction("CHKDOSS-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            bschcrossrelation30.setAction("CHKTRSF-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            bschcrossrelation30.setAction("CHKCCB3-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            bschcrossrelation30.setAction("CHKCCB4-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            bschcrossrelation30.setAction("CHKMPPF-2;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            bschcrossrelation30.setAction("CTAABER-1;SELECTED;BOOLEAN;EQ;VALUE;true");
//            bschcrossrelation30.setAction("CTAABER;CONTEXT;ALPHANUMERIC;EQ;VALUE;A");
//            bschcrossrelation30.setAction("CTAABER-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation30.setAction("CTAPROP-2;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation30.setAction("CCCABE-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;IREQ");
//            bschcrossrelation30.setAction("CCCPRO-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;IREQ");
//            bschcrossrelation30.setAction("CCC(1-4);CONTEXT;VALUE;EQ;BCO;CONTEXT");
//            bschcrossrelation30.setAction("CCC(5-8);CONTEXT;VALUE;EQ;AGE;CONTEXT");
//            bschcrossrelation30.setAction("CCC(9-22);CONTEXT;ALPHANUMERIC;EQ;VALUE;NULL");
//            bschcrossrelation30.setAction("CHKPROS-1;SELECTED;BOOLEAN;EQ;VALUE;false");
//            bschcrossrelation30.setAction("CHKPROS-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            bschcrossrelation30.setAction("CHKSCEP-1;SELECTED;BOOLEAN;EQ;VALUE;false");
//            bschcrossrelation30.setAction("CHKSCRT-1;SELECTED;BOOLEAN;EQ;VALUE;false");
//            bschcrossrelation30.setAction("CHKSCEP-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            bschcrossrelation30.setAction("CHKSCRT-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            panelPadre.add(bschcrossrelation30);
//            BSCHCrossRelation bschcrossrelation31 = new BSCHCrossRelation();
//            bschcrossrelation31.setName("Relation32");
//            bschcrossrelation31.setCondition("INDCCB4;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschcrossrelation31.setAction("CHKCCB4-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation31.setElseAction("CHKCCB4-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            panelPadre.add(bschcrossrelation31);
//            BSCHCrossRelation bschcrossrelation32 = new BSCHCrossRelation();
//            bschcrossrelation32.setName("Relation33");
//            bschcrossrelation32.setCondition("INDMPPF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschcrossrelation32.setAction("CHKMPPF-2;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation32.setElseAction("CHKMPPF-2;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            panelPadre.add(bschcrossrelation32);
//            BSCHCrossRelation bschcrossrelation33 = new BSCHCrossRelation();
//            bschcrossrelation33.setName("Relation34");
//            bschcrossrelation33.setCondition("INDTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschcrossrelation33.setAction("CHKTRSF-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation33.setElseAction("CHKTRSF-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            panelPadre.add(bschcrossrelation33);
//            BSCHCrossRelation bschcrossrelation34 = new BSCHCrossRelation();
//            bschcrossrelation34.setName("Relation35");
//            bschcrossrelation34.setCondition("QTETERM;CONTEXT;NUMERIC;EQ;VALUE;0");
//            bschcrossrelation34.setAction("QTDTERM-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            panelPadre.add(bschcrossrelation34);
//            BSCHCrossRelation bschcrossrelation35 = new BSCHCrossRelation();
//            bschcrossrelation35.setName("Relation36");
//            bschcrossrelation35.setCondition("CHKTRSF;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschcrossrelation35.setCondition("QTETERM;CONTEXT;NUMERIC;GE;VALUE;1");
//            bschcrossrelation35.setAction("QTDTERM-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation35.setElseAction("QTDTERM-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            panelPadre.add(bschcrossrelation35);
//            BSCHCrossRelation bschcrossrelation36 = new BSCHCrossRelation();
//            bschcrossrelation36.setName("Relation37");
//            bschcrossrelation36.setCondition("INDPROS;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschcrossrelation36.setAction("CHKPROS-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation36.setElseAction("CHKPROS-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            panelPadre.add(bschcrossrelation36);
//            BSCHCrossRelation bschcrossrelation37 = new BSCHCrossRelation();
//            bschcrossrelation37.setName("Relation38");
//            bschcrossrelation37.setCondition("PRODSER(1-1);CONTEXT;ALPHANUMERIC;EQ;VALUE;2||errores.MPE3068;CONTEXT;ALPHANUMERIC;NE;VALUE;NULL");
//            bschcrossrelation37.setAction("VLPREMIOM;CONTEXT;ALPHANUMERIC;EQ;VALSCP;CONTEXT");
//            panelPadre.add(bschcrossrelation37);
//            BSCHCrossRelation bschcrossrelation38 = new BSCHCrossRelation();
//            bschcrossrelation38.setName("Relation39");
//            bschcrossrelation38.setCondition("PRODSER(1-1);CONTEXT;ALPHANUMERIC;EQ;VALUE;3");
//            bschcrossrelation38.setCondition("BRBW471;LAST_PROCESS_STATUS;BOOLEAN;EQ;VALUE;TRUE");
//            bschcrossrelation38.setAction("VLPREMIOM;CONTEXT;ALPHANUMERIC;EQ;VLRMSCP;CONTEXT");
//            panelPadre.add(bschcrossrelation38);
//            BSCHCrossRelation bschcrossrelation39 = new BSCHCrossRelation();
//            bschcrossrelation39.setName("Relation40");
//            bschcrossrelation39.setCondition("INDSCEP;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschcrossrelation39.setAction("CHKSCEP-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation39.setElseAction("CHKSCEP;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            panelPadre.add(bschcrossrelation39);
//            BSCHCrossRelation bschcrossrelation40 = new BSCHCrossRelation();
//            bschcrossrelation40.setName("Relation41");
//            bschcrossrelation40.setCondition("INDSCRT;CONTEXT;ALPHANUMERIC;EQ;VALUE;S");
//            bschcrossrelation40.setAction("CHKSCRT-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;OPT");
//            bschcrossrelation40.setElseAction("CHKSCRT-1;BEHAVIOUR;ALPHANUMERIC;EQ;VALUE;RDONLY");
//            panelPadre.add(bschcrossrelation40);
//            BSCHCrossRelation bschcrossrelation41 = new BSCHCrossRelation();
//            bschcrossrelation41.setName("Relation42");
//            bschcrossrelation41.setCondition("INDCRD;CONTEXT;ALPHANUMERIC;EQ;VALUE;S||INDCRD;CONTEXT;ALPHANUMERIC;EQ;VALUE;I");
//            bschcrossrelation41.setAction("CAMP148;CONTEXT;ALPHANUMERIC;EQ;VALUE;NULL");
//            bschcrossrelation41.setAction("CCBVCTO;CONTEXT;ALPHANUMERIC;EQ;VALUE;NULL");
//            bschcrossrelation41.setAction("CCBDIAD;CONTEXT;ALPHANUMERIC;EQ;VALUE;NULL");
//            bschcrossrelation41.setAction("TAXANOR;CONTEXT;NUMERIC;EQ;VALUE;NULL");
//            bschcrossrelation41.setAction("CCBJURA;CONTEXT;NUMERIC;EQ;VALUE;NULL");
//            bschcrossrelation41.setAction("CETMESE;CONTEXT;NUMERIC;EQ;VALUE;NULL");
//            bschcrossrelation41.setAction("PCCET;CONTEXT;NUMERIC;EQ;VALUE;NULL");
//            panelPadre.add(bschcrossrelation41);
//            BSCHCrossRelation bschcrossrelation42 = new BSCHCrossRelation();
//            bschcrossrelation42.setName("Relation43");
//            bschcrossrelation42.setCondition("CAMPO12(13-15);CONTEXT;ALPHANUMERIC;EQ;VALUE;NULL");
//            bschcrossrelation42.setAction("CAMPO12(13-15);CONTEXT;ALPHANUMERIC;EQ;VALUE;-");
//            panelPadre.add(bschcrossrelation42);
//            BSCHCrossRelation bschcrossrelation43 = new BSCHCrossRelation();
//            bschcrossrelation43.setName("Relation44");
//            bschcrossrelation43.setCondition("CTAPROP-2;SELECTED;BOOLEAN;EQ;VALUE;true");
//            bschcrossrelation43.setAction("CODENTR;CONTEXT;ALPHANUMERIC;EQ;VALUE;P");
//            panelPadre.add(bschcrossrelation43);
//            BSCHCrossRelation bschcrossrelation44 = new BSCHCrossRelation();
//            bschcrossrelation44.setName("Relation45");
//            bschcrossrelation44.setCondition("CTAABER-1;SELECTED;BOOLEAN;EQ;VALUE;true");
//            bschcrossrelation44.setAction("CODENTR;CONTEXT;ALPHANUMERIC;EQ;VALUE;A");
//            panelPadre.add(bschcrossrelation44);
//            return panelPadre;
//        }
//        catch(Exception exception)
//        {
//            System.err.println("ERROR: An exception was thrown:");
//            exception.printStackTrace();
//            return null;
//        }
//    }
//
//    public static String version()
//    {
//        return "1.0";
//    }
//
//    private ClassLoader classLoader;
//    private BSCHOperationPanel panelPadre;
//}
